config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts, only: [:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save

    redirect_to @post
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container mt-5">
  <h1>記事一覧</h1>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>タイトル</th>
        <th>内容</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post.id, post_path(post) %></td>
          <td><%= post.title %></td>
          <td><%= post.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to '新規作成', new_post_path, class: 'btn btn-primary' %>
</div>

app/views/posts/new.html.erb
<div class="container mt-5">
  <h1>記事作成</h1>
  <%= form_for @post do |f| %>
  <div class="form-group">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
      <%= f.label :content, "内容" %>
      <%= f.text_area :content, class: 'form-control' %>
  </div>
  <%= f.submit '保存', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container mt-5">
  <h1>記事詳細</h1>
  <h2><%= @post.title %></h2>
  <p><%= @post.content %></p>
  <%= link_to '一覧に戻る', posts_path, class: 'btn btn-secondary' %>
</div>